### PR TITLE
added modal for login

### PR DESCRIPTION
**Pull request by rahilsmd**
screenshot from 2016-11-01 15-42-57

### CODE REVIEW

**Comment by ananyo2012** [comment]
@rahilsmd Please remove the "# users have already registered" Just keep register Now. Also make the social buttons like http://ank.mntc.in/events/tt/ Keep the icon and beside that keep the text "Sign with Facebook". Also keep some left and right padding around the button and center them.

**Comment by ananyo2012** [comment]
Also please give some padding-top so that the modal is is placed little below

**Comment by rahilsmd** [comment]
centering and padding makes the buttons overlap in iphone 5s. So , I I just changed the icons

**Comment by ananyo2012** [comment]
OK fine. In the event description page can you remove the text from facebook, twitter and google+ buttons? just keep then simple like the whatsapp button. Also make the Problem statement link a bootstrap button as well. Use a different class though. Make it .btn-info ?

**Comment by ananyo2012** [comment]
Also can you squash all these commits so that there is just one commit?

**Comment by ghoshbishakh** [comment]
closing as ANK frontend is irrelevant

**Pull request closed without merging**
