### PR TITLE
Event access while logged in as superuser

### LINKED ISSUE #44: Unable to open the event description when logged on from admin profile
The admin profile has to be logged out before viewing the event description of each event, or else an error is displayed.

### PR DESCRIPTION
**Pull request by nkprince007**
Profile model adjusted to save information when User model's save method is triggered.

Fixes #44

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@nkprince007 wow I am unaware of how signals work :P Ill try to review it. But merge if yourself if I forget to do so. Keep every PR alive for atleast 3 days before merging so that everyone can have a say in it.

**Comment by nkprince007** [comment]
Sure, bro. Either way I can't merge unless someone reviews it. :stuck_out_tongue:

**Comment by ghoshbishakh** [comment]
@nkprince007 ah I see :P well I can blindly approve :P

**Comment by nkprince007** [comment]
Well, I'm just receiving the broadcasted signal for [post_save](https://docs.djangoproject.com/en/1.10/ref/signals/#post-save) on `User` model. I added two methods just for clarity, if you want me to merge them into one, I'd do that. I think I should also add a `pre_delete` hook for the linked `Profile` model. And basically, connect them for Social Login too. What do you think @ghoshbishakh ?

**Comment by ghoshbishakh** [comment]
This is unsafe I guess. If someone logins via social login and does not fill the profile form then also the profile will be created as far as I understand. This is not desirable. Please check this usecase.

**Comment by nkprince007** [comment]
Yeah, I feel that we should also improvise on how social login is handled. I feel that it's better to have a receive a full profile from the user, while autofilling the user details made available via social login, so that we could maintain the consistency.

**Comment by ghoshbishakh** [comment]
@nkprince007 All relevant details are already filled up. You cannot pull all details from social media.

**Comment by nkprince007** [comment]
Yeah, I understand that. I'm just saying that when we just provide a single form for `User` and `Profile` models, and if someone wishes to use social auth, we would fill in the details available and ask the user to fill in the remaining ones.

**Comment by ghoshbishakh** [comment]
@nkprince007 I don't think any relevant details can be fetched as such.

**Comment by nkprince007** [comment]
@ghoshbishakh I'm referring to something similar to [this](http://javaguirre.me/2013/11/06/creating-a-user-profile-in-python-social-auth-in-django/)

**Comment by ghoshbishakh** [comment]
nope gender locale location are not there.

**Comment by ghoshbishakh** [comment]
I don't think it would be so much benificial. However you can open an issue for discussion. But not in this PR.

**Comment by nkprince007** [comment]
Looks okay now? @ghoshbishakh

**Comment by ghoshbishakh** [comment]
@nkprince007 good! LGTM!

**Comment by nkprince007** [comment]
I already checked it @ghoshbishakh

**Comment by nkprince007** [comment]
Merge? @ghoshbishakh

**Pull request merged**
