### PR TITLE
Add tests for Python 3.6 and change codecov conf

### PR DESCRIPTION
**Pull request by ghoshbishakh**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@nkprince007 check the PR please

@akshatnitd You will find some interesting test results here 😉 One template is missing.

**Comment by akshatnitd** [comment]
@ghoshbishakh Yes, the ReachUs template is missing. Should I go ahead and create an issue for that, and subsequently solve it as well?

**Comment by ghoshbishakh** [comment]
@akshatnitd yes make a quick PR please?

**Comment by akshatnitd** [comment]
@ghoshbishakh Doing it asap (y)

**Comment by akshatnitd** [comment]
@ghoshbishakh Done :+1: Check out PR #110

**Comment by ghoshbishakh** [comment]
@akshatnitd Thanks! As you can see python 3.5 build is now green!
https://travis-ci.org/NIT-dgp/festcms/builds/199698382

**Comment by akshatnitd** [comment]
@ghoshbishakh Great :smile:

**Comment by ghoshbishakh** [comment]
@nkprince007 all green! Review!

**Comment by nkprince007** [comment]
@ghoshbishakh LGTM!

**Comment by nkprince007** [comment]
@ghoshbishakh do consider once about the usage of `pytest` with `pytest-cov` and `pytest-django` in conjunction. 
eg: https://gitlab.com/gitmate/gitmate-2/blob/master/.gitlab-ci.yml

**Comment by ghoshbishakh** [comment]
@nkprince007 yes sure tell me the benifits

**Comment by nkprince007** [comment]
`pytest-cov` runs on the `pytest` configuration itself, it checks for coverage following our tests and does not report coverage on the untested modules, IMO it's the better way.
Coverage reports in console itself, making it easier for developers to check for issues.

**Pull request merged**
