### PR TITLE
Renamed sponsor to Sponsor

### PR DESCRIPTION
**Pull request by ankan17**
Made necessary changes in regards to renaming sponsor to Sponsor in models.py, views.py and admin.py

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@ankan17 
You need to change this too:
https://github.com/NIT-dgp/festcms/blob/master/festflow/views.py#L46

**Comment by ghoshbishakh** [comment]
@ankan17 
You need to change this too:
https://github.com/NIT-dgp/festcms/blob/master/festflow/views.py#L46

**Comment by ankan17** [comment]
@ghoshbishakh Changed it

**Comment by ghoshbishakh** [comment]
@ankan17 please change your commit message.

Read this one:
http://chris.beams.io/posts/git-commit/

Use somthing like 
```
Rename sponsor model to Sponsor

Changed the name in all files. Fixes #102
```

**Comment by ghoshbishakh** [comment]
@ankan17 If you face any problem regarding changing the commit message then please do ask in the group. People will be there to help you! Great job btw!

**Comment by ghoshbishakh** [comment]
@ankan17 any problems?

**Comment by ankan17** [comment]
@ghoshbishakh Issue addressed

**Comment by ghoshbishakh** [comment]
@nkprince007 can you check this once and merge?

**Comment by ghoshbishakh** [comment]
@nkprince007 you there?

**Comment by nkprince007** [comment]
@ghoshbishakh, sorry for the delay, I was on a vaction. 😅

**Comment by nkprince007** [comment]
LGTM! @ghoshbishakh @ankan17.

**Comment by ghoshbishakh** [comment]
@nkprince007 thanks! @ankan17 good work!

**Pull request merged**
