### PR TITLE
Update urls.py

### PR DESCRIPTION
**Pull request by modivivek**
In urls.py of festflow the event page has a wrong comment.It is corrected.

### CODE REVIEW

**Comment by modivivek** [comment]
In settings.py.example from urllib.parse import urlparse is commented as it is openshift specific setting.

**Comment by modivivek** [comment]
sponsor name displayed instead of sponsor object #39

**Comment by ghoshbishakh** [comment]
@modivivek sorry to say but you are only allowed to fix one newcomer issue. Please reset these commits and solve a single newcomer issue.

**Comment by ghoshbishakh** [comment]
@modivivek after fixing the newcomer issue you can check other issues of greater difficulty or make a feature request and implement it.

**Comment by ghoshbishakh** [comment]
@modivivek please resolve the conflicts and update this PR

**Comment by modivivek** [comment]
can u pls point out where the conflicts are??.. @ghoshbishakh

**Comment by ghoshbishakh** [comment]
@modivivek it is a long process. ask in the gitter channel

**Comment by ghoshbishakh** [comment]
@modivivek please do update this PR else I will be closing it in 3 days

The steps to resolve conflicts are:
Usually you have to do `git checkout -b mybranch` to move to a new branch.
Then `git checkout master`
`git log`
`git reset --hard <sha of the last commit before your commits>`
`git pull <nitDgpRemote> master`
`git checkout mybranch`
`git rebase master`
Now resolve the conflict
`git add .`
`git rebase --continue`
`git push <yourFork> mybranch`

**Comment by nkprince007** [comment]
Closing the PR due to inactivity @ghoshbishakh

**Pull request closed without merging**
