### PR TITLE
Admin: add a WYSIWYG editor for admin section

### LINKED ISSUE #63: Admin: add a WYSIWYG editor for editing about section in admin panel

### PR DESCRIPTION
**Pull request by nkprince007**
Fixes #63

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@nkprince007 amend the commit and put a more descriptive commit message.

# The seven rules of a great git commit message

Separate subject from body with a blank line
Limit the subject line to 50 characters
Capitalize the subject line
Do not end the subject line with a period
Use the imperative mood in the subject line
Wrap the body at 72 characters
Use the body to explain what and why vs. how

Detailed post is here:

http://chris.beams.io/posts/git-commit/

**Comment by ghoshbishakh** [comment]
@nkprince007 you did not add ckeditor in your installed app settings in settings.py.example

**Comment by nkprince007** [comment]
Oops, forgot about it.

**Comment by abhsag24** [comment]
awesome :P

**Comment by ghoshbishakh** [comment]
@nkprince007 dont you think that using `RichTextField()` will be a better way to use the editor?

**Comment by nkprince007** [comment]
I thought that so, but didn't implement it that way, because it required model change. But, if that's okay, I will reimplement it with a `RichTextField()`

**Comment by ghoshbishakh** [comment]
@nkprince007 things are working good! but I cant seem to find how to upload images. Is there a way?

**Comment by nkprince007** [comment]
Give it a spin now @ghoshbishakh

**Comment by ghoshbishakh** [comment]
@nkprince007 I am getting a template does not exist error on browsing for images

**Comment by nkprince007** [comment]
@ghoshbishakh we need to do collectstatic first :)

**Comment by ghoshbishakh** [comment]
@nkprince007 I am sure we dont.

**Comment by ghoshbishakh** [comment]
screenshot from 2016-11-20 19-21-14

**Comment by ghoshbishakh** [comment]
@nkprince007 please add `ckeditor_uploader` in settings.py.example

**Comment by ghoshbishakh** [comment]
@nkprince007 you do need to take these things carefully if you want to be a maintainer 😄

**Comment by nkprince007** [comment]
Sorry about that 😟

**Comment by ghoshbishakh** [comment]
@nkprince007 Last change:
Put a comment in settings.py.example 
# ckeditor settings

Thank you for your patience

**Comment by nkprince007** [comment]
Will do that soon as I finish my dinner and get back to my room. Sorry to keep you waiting

**Comment by ghoshbishakh** [comment]
@nkprince007 are no problem. Take you time.

**Comment by nkprince007** [comment]
@ghoshbishakh done :)

**Comment by ghoshbishakh** [comment]
LGTM! Thanks @nkprince007 for the hard work!

**Pull request merged**
