### PR TITLE
Change the event view template to display the name

### PR DESCRIPTION
**Pull request by akshatnitd**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@akshatnitd wow! :blush: 
Can you post a screenshot of how this is working?

**Comment by ananyo2012** [comment]
Same here too. Follow suggestion as in https://github.com/NIT-dgp/chrome-search-extension/pull/11#issuecomment-260691762. Here is a good documentation on how to write good commit messages http://chris.beams.io/posts/git-commit/

**Comment by akshatnitd** [comment]
@ghoshbishakh Here goes the screenshot!


@ananyo2012 Thanks!

**Comment by ghoshbishakh** [comment]
@akshatnitd looks awesome!!! :fireworks:

**Comment by ananyo2012** [comment]
Great work @akshatnitd Celebrate your first PR at https://twitter.com/yourfirstpr by tweeting @yourfirstpr if you have a twitter account :smiley:

**Pull request merged**
