### PR TITLE
Make about section generic

### LINKED ISSUE #30: Make About section generic
TSIA

### PR DESCRIPTION
**Pull request by nkprince007**
Fixes #30

### CODE REVIEW

**Comment by nkprince007** [comment]
Need help bro..

**Comment by ghoshbishakh** [comment]
@nkprince007 I would suggest you start doing it in another branch. And make a different PR then?

**Comment by ghoshbishakh** [comment]
@nkprince007 since this is not a newcomer issue I want you to do things in a different branch

**Comment by nkprince007** [comment]
Ok, bro.

**Comment by nkprince007** [comment]
Do I close this request then?

**Comment by ghoshbishakh** [comment]
@nkprince007 yes and no need to add AboutAdmin

**Comment by nkprince007** [comment]
Ok, bro.

**Pull request closed without merging**
