### PR TITLE
changed line in read.md

### PR DESCRIPTION
**Pull request by hasan356**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@hasan356 hi thanks for the great work! :smile: But there is a problem. You have to resolve the conflict here.
You can ask in gitter channel how to resolve that.

Usually you have to do `git checkout -b mybranch` to move to a new branch.
Then `git checkout master`
`git log`
`git reset --hard <sha of the last commit before your commits>`
`git pull <nitDgpRemote> master`
`git checkout mybranch`
`git rebase master`
Now resolve the conflict
`git add .`
`git rebase --continue`
`git push <yourFork> mybranch`

Then PR!! done!

**Comment by ghoshbishakh** [comment]
@hasan356 have you tried to resolve the conflict?

**Comment by hasan356** [comment]
i am actually little bit confused what conflict i hv to resolve

**Comment by ghoshbishakh** [comment]
@hasan356 you have to pull from upstream as your master branch is out of date. You can refer to this PR and ask questions in the gitter channel.

**Comment by ghoshbishakh** [comment]
@hasan356 
Usually you have to do `git checkout -b mybranch` to move to a new branch.
Then `git checkout master`
`git log`
`git reset --hard <sha of the last commit before your commits>`
`git pull <nitDgpRemote> master`
`git checkout mybranch`
`git rebase master`
Now resolve the conflict
`git add .`
`git rebase --continue`
`git push <yourFork> mybranch`

Then PR!! done!

**Comment by hasan356** [comment]
actually can u say what to do in git log

**Comment by ghoshbishakh** [comment]
@hasan356 you just have to do a rebase! :smile: Some changes that are present in this PR are already done in the codebase. So you have to do a rebase to remove the redundant changes. That will clear the conflict.

**Comment by nkprince007** [comment]
I'm closing this PR due to inactivity @ghoshbishakh.

**Pull request closed without merging**
