### PR TITLE
Make contactUrl field optional in organizerMember model fixes #47

### LINKED ISSUE #47: Contact url should be optional in organizerMember model
contactURL field should have blank=True and null=True parameters to make it optional.

### PR DESCRIPTION
**Pull request by ShreyasheeS**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@ShreyasheeS great work! :smile: 
But since it is not a newcomer bug I insist you to put a better commit message.
For example the message should be like:
"
Make contactUrl field optional in organizerMember model

fixes #47
"

Here #47 points to the issue it addresses
use `git commit --amend` to change your commit message.
Then `git push -f`

**Comment by ghoshbishakh** [comment]
@ShreyasheeS check this post to learn more about commit messages:
http://chris.beams.io/posts/git-commit/

**Comment by ShreyasheeS** [comment]
@ghoshbishakh Thank you for the reference. Will this work?

**Comment by ghoshbishakh** [comment]
@ShreyasheeS no I am afraid you changed the title of this PR. I need you to change your commit message. Using `git commit --amend`

**Comment by ghoshbishakh** [comment]
@ShreyasheeS  LGTM! thanks :smile:

**Comment by nkprince007** [comment]
@ghoshbishakh model has changed, but migrations were not committed here. :P

**Comment by ghoshbishakh** [comment]
@nkprince007 Thanks! Include these migrations in your PR too!

**Pull request merged**
